# Generated by Django 6.0.4 on 2026-04-28 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenPlaySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("capacity", models.PositiveIntegerField(default=10)),
                ("fee", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("full", "Full"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="openplay_sessions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="OpenPlayParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("removed", "Removed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="openplay_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="openplay.openplaysession",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="openplaysession",
            index=models.Index(
                fields=["date", "status"], name="openplay_op_date_c89363_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="openplayparticipant",
            index=models.Index(
                fields=["session", "status"], name="openplay_op_session_1c9d03_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="openplayparticipant",
            unique_together={("session", "user")},
        ),
    ]
