# Generated by Django 6.0.4 on 2026-05-03 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openplay", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="openplayparticipant",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="openplayparticipant",
            name="participant_name",
            field=models.CharField(
                blank=True,
                help_text="Used for walk-in participants without an account.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="openplayparticipant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="openplay_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="openplayparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("session", "user"),
                name="unique_session_registered_user",
            ),
        ),
    ]
