# Generated by Django 6.0.4 on 2026-05-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_remove_rentalrecord_user_rentalrecord_notes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rentalrecord",
            old_name="hours",
            new_name="quantity",
        ),
    ]
