# Generated by Django 6.0.4 on 2026-08-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_transaction_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                blank=True, help_text="e.g. gcash, card, qrph, onsite", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="provider",
            field=models.CharField(
                choices=[
                    ("paymongo", "PayMongo (Online)"),
                    ("onsite", "On-site / Manual"),
                ],
                default="onsite",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="provider_checkout_id",
            field=models.CharField(
                blank=True,
                help_text="PayMongo checkout session id (cs_...)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="provider_payment_id",
            field=models.CharField(
                blank=True,
                help_text="PayMongo payment id (pay_...)",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Payment"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                    ("waived", "Waived"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
