# Generated by Django 6.0.4 on 2026-05-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="announcement",
            name="announcemen_is_pinn_6f4cb5_idx",
        ),
        migrations.AddField(
            model_name="announcement",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Uncheck to take down this announcement."
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="level",
            field=models.CharField(
                choices=[
                    ("info", "Info (Blue)"),
                    ("sale", "Sale (Green)"),
                    ("warning", "Warning (Yellow)"),
                ],
                default="info",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="body",
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="image",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="is_pinned",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="visibility",
        ),
    ]
