# Generated by Django 6.0.4 on 2026-05-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0002_alter_announcement_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="level",
            field=models.CharField(
                choices=[
                    ("info", "Info (Blue)"),
                    ("success", "Sale (Green)"),
                    ("warning", "Warning (Yellow)"),
                ],
                default="info",
                max_length=20,
            ),
        ),
    ]
